/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppBarSearch: typeof import('./resources/js/@core/components/AppBarSearch.vue')['default']
    AvatarGroup: typeof import('./resources/js/components/AvatarGroup.vue')['default']
    CardStatisticsHorizontal: typeof import('./resources/js/@core/components/cards/CardStatisticsHorizontal.vue')['default']
    CardStatisticsVertical: typeof import('./resources/js/@core/components/cards/CardStatisticsVertical.vue')['default']
    CardStatisticsWithImages: typeof import('./resources/js/@core/components/cards/CardStatisticsWithImages.vue')['default']
    ConfirmationDialog: typeof import('./resources/js/components/ConfirmationDialog.vue')['default']
    CreateButton: typeof import('./resources/js/components/CreateButton.vue')['default']
    CustomSnackbar: typeof import('./resources/js/components/SnackBarAlert/CustomSnackbar.vue')['default']
    ErrorHeader: typeof import('./resources/js/components/ErrorHeader.vue')['default']
    Export: typeof import('./resources/js/components/Export.vue')['default']
    ItemList: typeof import('./resources/js/components/Item/ItemList.vue')['default']
    ItemTable: typeof import('./resources/js/components/Item/ItemTable.vue')['default']
    MoreBtn: typeof import('./resources/js/@core/components/MoreBtn.vue')['default']
    MyTimeComponent: typeof import('./resources/js/components/MyTimeComponent.vue')['default']
    OrderBuyTable: typeof import('./resources/js/components/Order/OrderBuyTable.vue')['default']
    OrderConfirmedTable: typeof import('./resources/js/components/Order/OrderConfirmedTable.vue')['default']
    OrderPendingTable: typeof import('./resources/js/components/Order/OrderPendingTable.vue')['default']
    PendingPurchasesTable: typeof import('./resources/js/components/Purchases/PendingPurchasesTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Security: typeof import('./resources/js/components/Profile/Security.vue')['default']
    ShowPosts: typeof import('./resources/js/components/Post/ShowPosts.vue')['default']
    TableTeam: typeof import('./resources/js/components/TableTeam.vue')['default']
    TableUser: typeof import('./resources/js/components/TableUser.vue')['default']
    TableWorkCategory: typeof import('./resources/js/components/TableWorkCategory.vue')['default']
    TableWorkType: typeof import('./resources/js/components/TableWorkType.vue')['default']
    ThemeSwitcher: typeof import('./resources/js/@core/components/ThemeSwitcher.vue')['default']
    TimesheetComponent: typeof import('./resources/js/components/TimesheetComponent.vue')['default']
    UpgradeToPro: typeof import('./resources/js/components/UpgradeToPro.vue')['default']
    UserProfileHeader: typeof import('./resources/js/components/Profile/UserProfileHeader.vue')['default']
    UserTable: typeof import('./resources/js/components/User/UserTable.vue')['default']
  }
}
