/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ApexCardHorizontalEarn: typeof import('./resources/js/components/Dashboard/ApexCardHorizontalEarn.vue')['default']
    CardStatisticsHorizontal: typeof import('./resources/js/@core/components/cards/CardStatisticsHorizontal.vue')['default']
    CardStatisticsVertical: typeof import('./resources/js/@core/components/cards/CardStatisticsVertical.vue')['default']
    CardStatisticsWithImages: typeof import('./resources/js/@core/components/cards/CardStatisticsWithImages.vue')['default']
    ChartStatisticsType: typeof import('./resources/js/components/AdminDashboard/ChartStatisticsType.vue')['default']
    ConfirmedItemPurchasesTable: typeof import('./resources/js/components/Purchases/ConfirmedItemPurchasesTable.vue')['default']
    ConfirmedServicePurchasesTable: typeof import('./resources/js/components/Purchases/ConfirmedServicePurchasesTable.vue')['default']
    CustomSnackbar: typeof import('./resources/js/components/SnackBarAlert/CustomSnackbar.vue')['default']
    DonutChartForStatus: typeof import('./resources/js/components/AdminDashboard/DonutChartForStatus.vue')['default']
    EarnWeeklyCard: typeof import('./resources/js/components/Dashboard/EarnWeeklyCard.vue')['default']
    ErrorHeader: typeof import('./resources/js/components/ErrorHeader.vue')['default']
    FollowingList: typeof import('./resources/js/components/Post/FollowingList.vue')['default']
    ItemList: typeof import('./resources/js/components/Item/ItemList.vue')['default']
    ItemTable: typeof import('./resources/js/components/Item/ItemTable.vue')['default']
    MoreBtn: typeof import('./resources/js/@core/components/MoreBtn.vue')['default']
    NavItem: typeof import('./resources/js/components/SearchItemNav/navItem.vue')['default']
    OrderItemConfirmedTable: typeof import('./resources/js/components/Order/OrderItemConfirmedTable.vue')['default']
    OrderItemPendingTable: typeof import('./resources/js/components/Order/OrderItemPendingTable.vue')['default']
    OrderServiceConfirmedTable: typeof import('./resources/js/components/Order/OrderServiceConfirmedTable.vue')['default']
    OrderServicePendingTable: typeof import('./resources/js/components/Order/OrderServicePendingTable.vue')['default']
    PendingItemPurchasesTable: typeof import('./resources/js/components/Purchases/PendingItemPurchasesTable.vue')['default']
    PendingServicePurchasesTable: typeof import('./resources/js/components/Purchases/PendingServicePurchasesTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScheduleMeetUp: typeof import('./resources/js/components/Dashboard/ScheduleMeetUp.vue')['default']
    Security: typeof import('./resources/js/components/Profile/Security.vue')['default']
    ServiceList: typeof import('./resources/js/components/Service/ServiceList.vue')['default']
    ServiceTable: typeof import('./resources/js/components/Service/ServiceTable.vue')['default']
    ShowPosts: typeof import('./resources/js/components/Post/ShowPosts.vue')['default']
    ThemeSwitcher: typeof import('./resources/js/@core/components/ThemeSwitcher.vue')['default']
    UserList: typeof import('./resources/js/components/Post/UserList.vue')['default']
    UserProfileDialog: typeof import('./resources/js/components/Profile/UserProfileDialog.vue')['default']
    UserProfileHeader: typeof import('./resources/js/components/Profile/UserProfileHeader.vue')['default']
    UserTable: typeof import('./resources/js/components/User/UserTable.vue')['default']
  }
}
