version: '3.9'
services:
  app:
    build:
      context: ./dockerfiles
      dockerfile: nginx.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - '80:80'
    volumes:
      - ./:/var/www/html:delegated
      - ./http_logs/:/var/log/nginx
    depends_on:
      - php
      - mysql
    networks:
      - laravel
  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www/html:delegated
    depends_on:
      - mysql
    networks:
      - laravel
  npm:
    image: node:18.15-alpine3.17
    user: node
    volumes:
      - ./:/var/www/html
    ports:
      - '5173:5173'
    working_dir: /var/www/html
    entrypoint: ['npm', 'run', 'dev2']
    networks:
      - laravel
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - '.docker/:/docker-entrypoint-initdb.d'
      - 'mysql:/var/lib/mysql'
    ports:
      - '3306:3306'
    networks:
      - laravel
networks:
  laravel:
volumes:
  mysql:
    driver: local
